name: Deploy to Azure App Service

on:
  push:
    branches:
      - main
  workflow_dispatch: # Permite la ejecución manual

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout del código
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Configurar Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18' # Cambia por la versión de Node.js de tu proyecto

    # 3. Instalar dependencias
    - name: Install dependencies
      run: npm install

    # 4. Generar build de Next.js
    - name: Build Next.js app
      run: npm run build

    # 5. Publicar en Azure App Service
    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: "giuliana-test" # Reemplaza con el nombre de tu App Service
        slot-name: "production"           # Cambia si usas un slot diferente
        azure_static_web_apps_api_token: ${{ secrets.AZURE_DEPLOYMENT_TOKEN }}
